In [139]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import r2_score

In [140]:
df = pd.read_csv('food_waste.csv')

In [141]:
df.head()

,ID,date,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg,staff_experience,waste_category,food_waste_kg
0,0,2022-12-19,196,13,27.887273,45.362854,0,0,7.740587,intermediate,dairy,28.946465
1,1,2023-11-21,244,15,10.317872,64.430475,1,0,42.311779,NaN,MeAt,51.549053
2,4,2022-02-01,148,16,27.714300,69.046113,1,0,41.184305,Beginner,MeAt,53.008323
3,5,2023-03-19,157,19,19.173902,46.292823,6,0,41.543492,Beginner,MeAt,48.621527
4,6,2022-07-18,297,10,26.375233,79.741064,0,0,26.525097,Intermediate,MEAT,44.156984

In [142]:
X= df.drop(columns=['food_waste_kg','date','ID','staff_experience','waste_category',])
y= df['food_waste_kg']

In [143]:
X

,meals_served,kitchen_staff,temperature_C,humidity_percent,day_of_week,special_event,past_waste_kg
0,196,13,27.887273,45.362854,0,0,7.740587
1,244,15,10.317872,64.430475,1,0,42.311779
2,148,16,27.714300,69.046113,1,0,41.184305
3,157,19,19.173902,46.292823,6,0,41.543492
4,297,10,26.375233,79.741064,0,0,26.525097
...,...,...,...,...,...,...,...
906,395,18,17.354199,45.138435,1,0,40.550668
907,483,11,24.912137,59.485091,6,0,36.470276
908,243,11,28.870945,70.508404,2,0,19.767203
909,406,10,19.061638,55.286642,0,0,28.560361
910,350,6,23.708015,51.351286,4,0,46.786860

In [144]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2, random_state=42
)

In [145]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [146]:
#LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.7475339458021363

In [147]:
#RIDGE
lr = Ridge(alpha=10)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.7467323961909241

In [148]:
# Lasso
reg = Lasso(alpha=0.01)
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.7476167677937595

In [149]:
# ElasticNet
reg = ElasticNet(alpha=0.005,l1_ratio=0.9)
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.7475472224023856